version: "3.7"

services:

  samba:
    image: dperson/samba # no hay tag con versiones, solo latest
    restart: always
    command: '-u "kent;2412" -s "media;/media;yes;no" -s "downloads;/downloads;yes;no"'
    stdin_open: true
    tty: true
    environment:
      - TZ=America/Argentina/Mendoza
    ports:
      - 139:139
    volumes:
      - ${MEDIA}:/media
      - ${STORAGE}/torrents:/downloads

  plex:
    image: jaymoulin/plex:1.30.1.6562
    expose:
      - 32400
      - 33400
    # Descomentar si NO usas network_mode: "host"
    ports:
     - 32400:32400
     - 33400:33400
    hostname: plex
    environment:
      - TZ=America/Argentina/Mendoza
    volumes:
      - ${CONFIG}/Plex/Plex Media Server:/root/Library/Application Support/Plex Media Server
      - ${MEDIA}:/media
      - ${CONFIG}/Plex/tmp:/tmp
    restart: unless-stopped
    # network_mode: "host" # Solo funciona en Linux

  jackett:
      image: linuxserver/jackett
      container_name: jackett
      environment:
        - PUID=998
        - PGID=100
        - TZ=America/Argentina/Mendoza
      volumes:
        - ${CONFIG}/Jackett:/config
        - ${STORAGE}/torrents:/downloads
      ports:
        - 9117:9117
      restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Mendoza
      - WEBUI_PORT=8080
    volumes:
      - ${CONFIG}/qBittorrent/path/to/appdata/config:/config
      - ${STORAGE}/torrents:/downloads
    ports:
      - 8080:8080
    restart: unless-stopped

  radarr:
      image: linuxserver/radarr
      container_name: radarr
      environment:
        - PUID=998
        - PGID=100
        - TZ=America/Argentina/Mendoza
        - UMASK_SET=022 #optional
      volumes:
        - ${CONFIG}/Radarr:/config
        - ${MEDIA}:/media/Peliculas
        - ${STORAGE}/torrents:/downloads
      ports:
        - 7878:7878
      restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=998
      - PGID=100
      - TZ=America/Argentina/Mendoza
      - UMASK_SET=022
    volumes:
      - ${CONFIG}/Sonarr:/config
      - ${MEDIA}:/media/Series
      - ${STORAGE}/torrents:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped